### PR TITLE
Make the API more IDE-friendly

### PR DESCRIPTION
**Pull request by LukBukkit**
With this pull request I want to improve the using of namespaces and class names. This makes the API more friendly for IDEs, because they can scan all classes and determine the realationships between them. Once this works they can offer useful features like autocompletion.
I hope I can help you with these changes 😃

### CODE REVIEW

**Comment by Pierozi** [comment]
We should not change the code to resolve this.

I think @camael24 already did a command to generate Stub no ?
It should be under https://github.com/hoaproject/Devtools

**Comment by Pierozi** [comment]
Here it this PR still open hoaproject/Devtools#6

**Comment by Metalaka** [comment]
Hi,
As said by @Pierozi, this kind of issue (it's not specific to `Hoa\Socket`) should be fixed by https://github.com/hoaproject/Devtools/pull/6

**Comment by Hywan** [comment]
@vonglasow We can probably close this issue and focus on hoaproject/Devtools#6, thoughts?

**Comment by vonglasow** [comment]
@Hywan and @Pierozi are rights we can improve integration in IDE in the issue hoaproject/Devtools#6 so I close this PR in benefit of this issue.

**Pull request closed without merging**
