### PR TITLE
Add `.gitignore` file

### PR DESCRIPTION
**Pull request by shulard**
Add a `.gitignore` file to the repo as defined in hoaproject/Central#22

### CODE REVIEW

**Comment by Hywan** [comment]
In the commit title, prefer:
> Add the `.gitignore` file.

**Comment by shulard** [comment]
Updated :)

**Comment by Hywan** [comment]
Sorry, can you add backtick (`) around the `.gitignore`?

**Comment by shulard** [comment]
Updated :)

**Comment by Hywan** [comment]
Perfect :-). Don't forget the `.` (point) at the end of the commit message, it's a sentence :wink:.

**Comment by shulard** [comment]
Of course, updated !

**Comment by Hywan** [comment]
@shulard Perfect!

**Comment by Hywan** [comment]
Should we use `/composer.lock` instead of `composer.lock` too? This is still at the root of the repository.

**Comment by shulard** [comment]
Good point, we only want to ignore the root files here...

**Comment by Hywan** [comment]
Need a rebase, only one commit is necessary.

**Comment by shulard** [comment]
I merged the commits.

**Comment by Hywan** [comment]
Perfect. The pattern is validated.

**Comment by shulard** [comment]
Ok, I start adding in all the repos

**Comment by Hywan** [comment]
:+1:

**Pull request merged**
